### PR TITLE
support additional fields and functions

### PR DESCRIPTION
**Pull request by dantrevino**
Add image field and add name and image getters.  Code checked out in clarity.tools, so hopefully it is correct.

### CODE REVIEW

**Comment by friedger** [comment]
I am fine with the additional field, however, the getter could be just a call to map_entry + deserialization:

```
curl -X POST -H 'Content-Type: application/json' -i 'http://testnet-master.blockstack.org:20443/v2/map_entry/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV/monsters/monsters?proof=0' --data '"0x0c000000010a6d6f6e737465722d69640100000000000000000000000000000001"'
```

**Comment by friedger** [comment]
Currently, only contracts-simple are deployed, waiting for the traits to be supported in testnet, coming with krypton.

**Comment by dantrevino** [comment]
> I am fine with the additional field, however, the getter could be just a call to map_entry + deserialization:
> 
> ```
> curl -X POST -H 'Content-Type: application/json' -i 'http://testnet-master.blockstack.org:20443/v2/map_entry/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV/monsters/monsters?proof=0' --data '"0x0c000000010a6d6f6e737465722d69640100000000000000000000000000000001"'
> ``` 

I didn't know there was a way to do this.  It makes more sense to get the whole map,  agreed.

**Comment by friedger** [comment]
image added in 01e18d0

**Pull request closed without merging**
